### ISSUE TITLE
Question on Visdom

### ISSUE THREAD

**Issue by amans191** [peto184/tp_3dgan_pytorch#1]
Hi, 

This is just a question about using visdom with FloydHub. From what I understand is that you need to run the visdom server while you do the training. But if your training is happening on the cloud, did you run the visdom server on the cloud to or how did you do this.

**Comment by peto184** [comment]
Hi,

this is a fork repo from https://github.com/rimchang/3DGAN-Pytorch. You might want to ask there. 
Personally i trained the network locally with running visdom server, so i'm not sure about the visdom on cloud.
